// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheTower.Models;

namespace TheTower.Migrations
{
    [DbContext(typeof(TowerContext))]
    [Migration("20250708224414_AddIndex")]
    partial class AddIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheTower.Models.Biome", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("RollNumber");

                    b.HasKey("ID");

                    b.ToTable("Biome");
                });

            modelBuilder.Entity("TheTower.Models.CRRoll", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MonsterId");

                    b.Property<int>("MonsterQTY");

                    b.Property<int>("RollNumber");

                    b.Property<int>("SessionId");

                    b.Property<int>("XP");

                    b.HasKey("ID");

                    b.ToTable("CRRoll");
                });

            modelBuilder.Entity("TheTower.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("RollNumber");

                    b.HasKey("ID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("TheTower.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemCost");

                    b.Property<string>("ItemName");

                    b.Property<string>("Vendor");

                    b.HasKey("ID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("TheTower.Models.Level", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BiomeID");

                    b.Property<int>("CRLevel");

                    b.Property<int>("EventID");

                    b.Property<int>("MonsterID");

                    b.Property<string>("Name");

                    b.Property<int>("RoomLevel");

                    b.Property<int>("SessionID");

                    b.HasKey("ID");

                    b.HasIndex("SessionID");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("TheTower.Models.Monster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChallengeRating");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Index");

                    b.Property<string>("Name");

                    b.Property<int>("RollNumber");

                    b.Property<string>("Source");

                    b.Property<int>("XP");

                    b.HasKey("ID");

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("TheTower.Models.MonsterCR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CRRollId");

                    b.Property<int>("MonsterId");

                    b.Property<int>("RollNo");

                    b.Property<int>("SessionId");

                    b.HasKey("ID");

                    b.ToTable("MonsterCR");
                });

            modelBuilder.Entity("TheTower.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Char");

                    b.Property<int>("Init");

                    b.Property<string>("Name");

                    b.Property<int>("SessionId");

                    b.HasKey("ID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("TheTower.Models.RoomRoll", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiceRoll");

                    b.Property<int>("RoomMove");

                    b.HasKey("ID");

                    b.ToTable("RoomRoll");
                });

            modelBuilder.Entity("TheTower.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentLevel");

                    b.Property<string>("DMName");

                    b.Property<int>("PlayerLevel");

                    b.Property<int>("PlayerQty");

                    b.Property<int>("SessionCode");

                    b.Property<int>("XP");

                    b.HasKey("ID");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("TheTower.Models.Level", b =>
                {
                    b.HasOne("TheTower.Models.Session")
                        .WithMany("LevelSetup")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
